---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-dep
  labels:
   {{- include "spring-petclinic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
     {{- include "spring-petclinic.labels" . | nindent 8 }}
    spec:
      containers:
        - name: spring-petclinic
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          resources:
          {{- toYaml .Values.app.computeres | nindent 12 }}
