apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinc
  labels:
    app: petclinc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinc
  template:
    metadata:
      labels:
        app: petclinc
    spec:
      containers:
        - name: petclinc
          image: petclinc:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV_VARIABLE_1
              value: value1
            - name: ENV_VARIABLE_2
              value: value2
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
