{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  minReplicas: {{ .Values.hpa.minrplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: spring-petclinic
  targetCPUUtilizationPercentage: {{ .Values.hpa.cuputi }}
{{- end -}}
