apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  labels:
   {{- include "spring-petclinic.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: spring-petclinic
  type: NodePort
